- name: Demo for creating docker containder from Ansible
  hosts: localhost
  tasks:
    - name: Create ubuntu container
      docker_container:
              name: "ubuntu{{item}}"
              hostname: "ubuntu{{item}}"
              image: "eash/ansible-ubuntu"
              ports:
                      - "200{{item}}:22"
                      - "800{{item}}:80"
              state: started
      with_sequence: start=1 end=3
    - name: Create centos container
      docker_container:
              name: "centos{{item}}"
              hostname: "centos{{item}}"
              image: "eash/ansible-centos"
              ports:
                      - "300{{item}}:22"
                      - "900{{item}}:80"
              state: started
      with_sequence: start=1 end=3
